### ISSUE TITLE
ni ge zz

### ISSUE THREAD

**Issue by piperck** [binderclip/coding-share#1]
hhh

**Comment by timlight** [comment]
@binderclip test

**Comment by timlight** [comment]
@binderclip test2

**Comment by piperck** [comment]
@binderclip 哈哈哈哈

**Comment by timlight** [comment]
@binderclip xixixi

**Comment by timlight** [comment]
@binderclip hohoho

**Comment by timlight** [comment]
@binderclip 看起来最靠谱的是手机 QQ 的提醒。不管收不收进文件夹都会提示。

**Comment by timlight** [comment]
@binderclip Spark 的手机和 Mac 版本也不错，只要不收进文件夹也都会提醒

**Comment by timlight** [comment]
Mac 上 Foxmail 的提示好弱啊，文件夹里的似乎不会提示的。

**Comment by timlight** [comment]
@binderclip Inbox 里面的会自动提示吗？Foxmail。啊，是会的。

**Comment by piperck** [comment]
垃圾啊

发自 Windows 邮件

On Dec 21, 2016, 1:02 PM +0800, timlight <notifications@github.com>, wrote:

Mac 上 Foxmail 的提示好弱啊，文件夹里的似乎不会提示的。

**Comment by timlight** [comment]
@binderclip 哈哈哈

**Comment by timlight** [comment]
@binderclip 那么就不用文件夹了，两边都用 Spark，DONE！

**Comment by binderclip** [comment]
close
